fix: implicit declarations, incompatible types, argv type
Fixed a few compiler warnings:

prot.c:13:7: warning: implicit declaration of function ‘setgroups’ [-Wimplicit-function-declaration]
chpst.c:80:7: warning: implicit declaration of function ‘setgroups’; did you mean ‘getgroups’? [-Wimplicit-function-declaration]
 - added #include <grp.h>, see: https://linux.die.net/man/2/setgroups

chkshsgr.c:11:19: warning: passing argument 2 of ‘getgroups’ from incompatible pointer type [-Wincompatible-pointer-types]
 - change 'short' to 'gid_t', see: https://linux.die.net/man/2/setgroups

pathexec_run.c:18:5: warning: implicit declaration of function ‘execve’ [-Wimplicit-function-declaration]
 - add #include <unistd.h>, see: http://man7.org/linux/man-pages/man2/execve.2.html

prot.c:17:10: warning: implicit declaration of function ‘setgid’; did you mean ‘getgrgid’? [-Wimplicit-function-declaration]
 - add #include <unistd.h>, see: https://linux.die.net/man/3/setgid

seek_set.c:9:7: warning: implicit declaration of function ‘lseek’ [-Wimplicit-function-declaration]
 - add #include <unistd.h>, see: https://linux.die.net/man/2/lseek

--------------------------------------

Fixed type of argv, from 'const char **argv' to 'char **argv'
This resolves a lot of compiler typecast warnings like:
pathexec_run.c:19:17: warning: passing argument 2 of ‘execve’ from incompatible pointer type [-Wincompatible-pointer-types]

NOTE: this change might be disputable and not obvious at first.
For arguments for argv as 'char **argv', see:

The C Programming Language, Kernighan & Ritchie, Second Edition,  Section 5.10, page 110
Command-line Arguments:  main(int argc, char *argv[])

From https://riptutorial.com/c/example/3675/original--hello--world---in-k-r-c
int main(int argc, char **argv)

From C/C++ Kompendium (DE), Markt+Technik Verlag 2000, page 576, Chapter 12, main() Parameter:
int main(int argc, char *argv[])

From http://www.cplusplus.com/articles/DEN36Up4/
int main(int argc, char* argv[]) // or char** argv

From https://ece.uwaterloo.ca/~dwharder/icsrts/C/05/
int main( int argc, char *argv[] )

At
https://stackoverflow.com/questions/5808679/why-is-main-argument-argv-of-type-char-rather-than-const-char
is argued, that:
 - argv isn't const, since it's being created at runtime
 - in certain cases you should be able to rewrite argv from you program

The main argument for this type change:
the argv is used in a call to execve, so the type should be declared as compatible
with execve parameters.  http://man7.org/linux/man-pages/man2/execve.2.html
defines:
int execve(const char *filename, char *const argv[], char *const envp[]);

so every argv defined as 'const char *const argv[]' was changed to:
'char *const argv[]'